name: Test

on:
    pull_request:
        branches: [ main ]

jobs:
    test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [ latest ]

        steps:
            - run: echo "No tests!"
